using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            string dnaString = "CTACGGGTGAAGTTCCGATGCAAATCCAACTGTATAATATCCGCAATGGGCTCTTCCAAGTTCAAGGTTTATACAGTGAACCAATTCGGAAATTAGGCGGCGCTACAGCCGCATTTCCCTTGTCTGACGAGCCGTCATACGGTACGCACCCGCATTGACGCATAACGGACCTCCTAAAGTAAACTCGAGTCCGATGGCTCTCATAACTTTCGGCAATCAGAAGCTCATCGTAGGGACCACCATCATCACGTCGACCAGGTTCCAGGACTAAATCTACTAGCACGATCACACCGGTGCAACATTAAGAAGTGCCTATCTCGAATCGCACCAAGCGCTGCACCTCAGAAGCACTCCATGTGTCAGCCAGAAATAGGGGTTGTTCGGCGGATTGAGTAGATGTATCTGCCATGGCCACAATCTCGGAGCAGCGCGCCCTACAGGGAATTACAGTTGTTTTACGGTGCAGTCACTTTGCGCCCCGTTCCGGCATTCCTAACCCGTCCTATACAATTACTTCCATGTAGATAAACAGTAACATTTTAGATCAGTGATAACGAGCGATGCATCAATTGTTGAGGAAGCTGTGCTATCAGACGCGATGTAGTTAGCGTTACTAGTCAACCCTGTCACAGTCGTTCGTACCACGTCTTTTGTGTCTTGGTAAGCTTTGCGATGCTTGCCGTATAGTGATTAAGAGCCTTCGGCCGGCTACAAAGATCGCCACGGATCGCAGCTATTGATGGCAATCTTTGCGAGCTGGACCCTGGGTCAAACGCTACCTCCGGACCCGAATGCCTAGGCCCAACTCAGCTTATATTCGGACGAGTATAGACGCGATCAGGAATCGAAGATTTCCTGTGTACGCTCTAACAGGCGAAACAATGTGTCGCCAGACTTCGGGGGGCATCAGCGCCCAGGCC";
            string rnaString = "";
            char[] dnaStringArray = dnaString.ToCharArray();

            foreach (char c in dnaStringArray)
            {
                if (c == 'T')
                {
                    rnaString += 'U';
                }
                else
                {
                    rnaString += c;
                }
            }

            Console.WriteLine($"{rnaString}");
            Console.ReadKey();
        }
    }
}
